=== iamzahariks/isit_1sem_kyar_syap/CML/lab12_completed/task3.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs ="http://www.w3.org/2001/XMLSchema">
<xs:element name="body">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="list">
            <xs:complexType>
            <xs:sequence>
                <xs:element name="item" maxOccurs="unbounded">
                    <xs:complexType>
                    <xs:sequence>
                        <xs:element name="img" type="xs:string"/>
                        <xs:element name="cost" type="xs:string"/>
                        <xs:element name="description" type="xs:string"/>
                    </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== iamzahariks/isit_1sem_kyar_syap/CML/lab12_completed/task3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="css/styles.css"?>

<body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="task3.xsd">
    <list>
        <item>
            <img></img>
            <cost> $1.49 </cost>
            <description> Вкуснейшие яблоки! </description>
        </item>

        <item>
            <img></img>
            <cost> $299 </cost>
            <description> Женёк с другой комнаты играет на гитаре просто, поэтому она здесь... </description>
        </item>

        <item>
            <img></img>
            <cost> $99 </cost>
            <description> Кросовки для крутых!!! </description>
        </item>

        <item>
            <img></img>
            <cost> $399 </cost>
            <description> Первый умный телефон! </description>
        </item>

        <item>
            <img></img>
            <cost> $49 </cost>
            <description> Персидский ковёр - очень дорогой ковёр. И именно в этом ковре... </description>
        </item>
    </list>
</body>
